[package]
name = "monkey-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
monkey-token = { path = "../token" }
monkey-lexer = { path = "../lexer" }
monkey-ast = { path = "../ast" }



